// <auto-generated />
using Dbtools.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Httpclient.Migrations
{
    [DbContext(typeof(DbContextSteam))]
    partial class DbContextSteamModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Dbtools.models.ItemPriceInfo", b =>
                {
                    b.Property<int>("PriceInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PriceInfoId"));

                    b.Property<decimal>("AvgPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SalesVolume")
                        .HasColumnType("int");

                    b.HasKey("PriceInfoId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("ItemPriceInfos", (string)null);
                });

            modelBuilder.Entity("Dbtools.models.SteamItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ItemId");

                    b.ToTable("SteamItems", (string)null);
                });

            modelBuilder.Entity("Dbtools.models.ItemPriceInfo", b =>
                {
                    b.HasOne("Dbtools.models.SteamItem", "SteamItem")
                        .WithOne("PriceInfo")
                        .HasForeignKey("Dbtools.models.ItemPriceInfo", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SteamItem");
                });

            modelBuilder.Entity("Dbtools.models.SteamItem", b =>
                {
                    b.Navigation("PriceInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
